package basicWeb;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public class Exercise11 {

	public static void main(String[] args) {
		//***************1. Launch  new Firefox browser ********************
		System.setProperty("webdriver.gecko.driver","C:\\Ejecutables\\Selenium\\geckodriver-v0.11.0-win64\\geckodriver.exe");
		WebDriver driver = new FirefoxDriver();
						
		//***************2. Open URL https://www.toolsqa.com/automation-practice-switch-windows/ ********************
		String baseURL= "https://www.toolsqa.com/automation-practice-switch-windows/";
		driver.get(baseURL);
						
		//***************3. Click on button "Alert box", it will open a pop up Window generated by JavaSript ********************
		 driver.findElement(By.id("alert")).click();;
		
		//***************4. Switch to alert window (Use 'SwitchTo()Alert() command ********************
		//Alert alert = driver.switchTo().alert();
		 driver.switchTo().alert();
		
		//***************5. Close pop up Window (Use accept command) ********************
		driver.close();
	}

}
